# Generated by Django 2.0.1 on 2018-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookreg',
            name='secret',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
